name: PlugManReloaded
version: '1.1-beta'
main: ru.milkyway.plugmanreloaded.PlugManReloaded
api-version: 1.16
author: vkusniy_milkyway
website: https://github.com/MilkyWayTop16/PlugManReloaded
folia-supported: true
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - packetevents
  - Vault

commands:
  plugmanreloaded:
    usage: /<command> help
    aliases:
      - plugman
      - plm

permissions:
  plugmanreloaded.admin:
    default: op
    children:
      plugmanreloaded.help: true
      plugmanreloaded.list: true
      plugmanreloaded.info: true
      plugmanreloaded.load: true
      plugmanreloaded.unload: true
      plugmanreloaded.reload: true
      plugmanreloaded.restart: true
      plugmanreloaded.enable: true
      plugmanreloaded.disable: true
      plugmanreloaded.usage: true
      plugmanreloaded.dump: true
      plugmanreloaded.hotswap: true
      plugmanreloaded.config: true
      plugmanreloaded.update: true
      plugmanreloaded.update.source: true
      plugmanreloaded.delete: true
      plugmanreloaded.download: true
      plugmanreloaded.notify: true
